import 'package:flutter/widgets.dart';
import 'package:pinyin/pinyin.dart'
    show ChineseHelper, PinyinFormat, PinyinHelper;

/// Sona keeps Simplified Chinese as the source language. Traditional Chinese
/// is derived with the bundled offline dictionary, while English uses reviewed
/// product copy. Missing English entries deliberately fall back to the source
/// text so a new control never becomes blank.
class SonaLocalizations {
  const SonaLocalizations(this.locale);

  final Locale locale;

  static SonaLocalizations of(BuildContext context) =>
      SonaLocalizations(Localizations.localeOf(context));

  String text(String source) {
    if (locale.languageCode == 'en') return _english[source] ?? source;
    if (locale.scriptCode == 'Hant') {
      return _traditional[source] ??
          ChineseHelper.convertToTraditionalChinese(source);
    }
    return _simplified[source] ?? source;
  }

  /// Localizes user-facing music metadata without changing the stored value.
  /// Chinese variants are losslessly converted. English keeps official Latin
  /// metadata as-is and uses title-cased Pinyin only when no Latin name exists.
  String metadata(String source) {
    final trimmed = source.trim();
    if (trimmed.isEmpty) return source;
    final normalized = trimmed.toLowerCase();
    if (const {
      'unknown artist',
      '未知歌手',
      '未标注歌手',
      '未標註歌手',
    }.contains(normalized)) {
      return text('未知歌手');
    }
    if (const {
      'unknown album',
      '未知专辑',
      '未知專輯',
      '未标注专辑',
      '未標註專輯',
    }.contains(normalized)) {
      return text('未标注专辑');
    }
    if (const {'local video', '本地视频', '本機影片'}.contains(normalized)) {
      return text('本地视频');
    }
    if (const {'standalone mv', '独立 mv', '獨立 mv'}.contains(normalized)) {
      return text('独立 MV');
    }
    if (locale.scriptCode == 'Hant') {
      return ChineseHelper.convertToTraditionalChinese(trimmed);
    }
    if (locale.languageCode == 'zh') {
      return ChineseHelper.convertToSimplifiedChinese(trimmed);
    }
    if (locale.languageCode != 'en' ||
        !RegExp(r'[\u3400-\u9FFF]').hasMatch(trimmed)) {
      return trimmed;
    }
    final pinyin = PinyinHelper.getPinyinE(
      trimmed,
      separator: ' ',
      defPinyin: '',
      format: PinyinFormat.WITHOUT_TONE,
    ).replaceAll(RegExp(r'\s+'), ' ').trim();
    return pinyin
        .split(' ')
        .map(
          (word) => word.isEmpty
              ? word
              : '${word.substring(0, 1).toUpperCase()}${word.substring(1)}',
        )
        .join(' ');
  }
}

extension SonaLocalizationContext on BuildContext {
  String tr(String source) => SonaLocalizations.of(this).text(source);
  String trArgs(String source, Map<String, String> arguments) {
    var result = tr(source);
    for (final entry in arguments.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value);
    }
    return result;
  }

  String metadata(String source) => SonaLocalizations.of(this).metadata(source);
}

const _simplified = <String, String>{
  'library_read_failed': '读取本地曲库失败，请重新打开 Sona 后重试。',
  'track_not_persisted': '这首歌曲尚未保存，无法识别。',
  'identification_in_progress': '正在识别这首歌曲，请稍候。',
  'identification_file_missing': '找不到本地文件，无法识别。',
  'identification_fingerprint_match': '已通过音频声纹找到匹配结果。',
  'identification_catalog_fallback_after_fingerprint': '声纹没有可靠命中，已用公开曲库完成后备校准。',
  'identification_catalog_fallback': '已用文件信息和公开曲库完成后备校准。',
  'identification_source_local_cleanup': '本地智能清洗',
  'identification_local_cleanup_explanation':
      '公开曲库没有可靠结果，仅根据标签和文件名给出建议，请确认后再应用。',
  'identification_local_cleanup_suggested': '没有查到可靠的联网结果，已生成本地清洗建议。',
  'identification_no_reliable_result': '没有找到可靠的识别结果，已保留原信息。',
  'identification_source_acoustid': 'AcoustID 音频声纹',
  'identification_acoustid_explanation': '根据音频内容匹配，与文件名无关。',
  'identification_source_musicbrainz': 'MusicBrainz 公开曲库',
  'identification_musicbrainz_explanation': '根据清洗后的曲名、歌手和时长进行联网校准，并非声纹命中。',
  'manual_edit': '手动编辑',
  'cover_file_missing': '找不到选择的封面文件。',
  'cover_file_type_unsupported': '请选择 JPG、PNG 或 WebP 图片。',
  'cover_file_too_large': '封面图片不能超过 12 MB。',
  'audio_file_required': '请先选择音频文件。',
  'audio_already_in_library': '这个音频文件已经在曲库中。',
  'unexpected_library_error': '操作未完成，请稍后重试。',
  'account_username_invalid': '请输入有效账号名。',
  'account_sign_in_incomplete': '登录没有完成，请重试。',
  'account_sign_in_success': '登录成功，正在检查云端数据。',
  'account_username_format_invalid': '账号名格式不正确。',
  'account_sign_up_incomplete': '账号创建没有完成，请确认云端已关闭邮箱验证后重试。',
  'account_sign_up_success': '账号创建成功，已经登录。',
  'account_signed_out': '已退出云账号，本地音乐不会受到影响。',
  'account_display_name_synced': '显示名称已同步。',
  'account_avatar_uploading': '正在上传头像…',
  'account_avatar_updated': '头像更新成功，登录其他设备后会自动恢复。',
  'account_cloud_not_configured': '云端尚未配置。',
  'account_sign_up_disabled': '云端注册入口尚未开启，请稍后重试。',
  'account_invalid_credentials': '账号名或密码不正确。',
  'account_username_taken': '这个账号名已被使用，请换一个账号名。',
  'account_service_unavailable': '账号服务暂时无法完成操作，请稍后重试。',
  'account_avatar_save_failed': '头像暂时无法保存到云端，请稍后重试。',
  'account_profile_update_failed': '云端资料暂时无法更新，账号仍保持登录，请稍后重试。',
  'account_operation_failed': '操作没有完成，请稍后重试。',
  'cloud_sign_in_required': '请先登录云账号。',
  'cloud_track_recycled': '已将“{title}”移入云端回收站。',
  'cloud_track_restored': '已恢复“{title}”。',
  'cloud_sync_planning': '正在整理同步计划…',
  'cloud_sync_preview': '待上传 {upload} 首、待下载 {download} 首、云端歌单待恢复 {playlistDownload} 个；{unchanged} 首无需变动。',
  'cloud_sync_preview_with_skipped': '待上传 {upload} 首、待下载 {download} 首、云端歌单待恢复 {playlistDownload} 个；{unchanged} 首无需变动。另有 {tooLarge} 首超过 50 MB，仍只保留在本机。',
  'cloud_sync_connecting': '正在连接云端…',
  'cloud_syncing_track': '正在同步“{title}”…',
  'cloud_syncing_rankings': '正在同步听歌排行…',
  'cloud_syncing_playlists': '正在同步歌单…',
  'cloud_sync_downloading_tracks': '正在下载云端曲目…',
  'cloud_sync_restoring_playlists': '正在恢复云端歌单…',
  'cloud_sync_complete': '同步完成',
  'cloud_sync_complete_changes': '同步完成：上传 {uploaded} 首，下载 {downloaded} 首。',
  'cloud_sync_complete_changes_with_skipped': '同步完成：上传 {uploaded} 首，下载 {downloaded} 首；{skippedLarge} 首超过 50 MB，仍只保留在本机。',
  'cloud_sync_complete_unchanged': '同步完成：本机与云端已经一致。',
  'cloud_sync_complete_unchanged_with_skipped':
      '同步完成：本机与云端已经一致；{skippedLarge} 首超过 50 MB，仍只保留在本机。',
  'cloud_sync_interrupted': '同步已中断，本地曲库不受影响。',
  'cloud_error_offline': '离线状态，无法连接至云端。',
  'cloud_error_invalid_credentials': '云账号登录状态已失效，请重新登录。',
  'cloud_error_permission': '云端拒绝了这次操作，请检查账号权限。',
  'cloud_error_connection': '暂时无法连接云端，请稍后重试。',
  'cloud_error_schema': '云端数据结构尚未完成配置。',
  'cloud_error_media': '云端媒体文件暂时不可用，请稍后重试。',
  'cloud_error_generic': '云同步暂时无法完成，请稍后重试。',
  'queue_source_local_library': '本地曲库',
  'queue_source_search': '搜索“{query}”',
  'queue_source_favorites': '我的收藏',
  'queue_source_videos': '有 MV',
  'queue_source_recent': '最近播放',
  'queue_source_rankings': '听歌排行',
  'queue_source_cloud_library': '云端资料库',
  'queue_source_playlist': '歌单《{playlist}》',
  'player_error_engine': '播放器发生错误，请重试。',
  'player_error_open_track_preserved_previous': '无法播放“{title}”，已继续保留上一首歌曲。',
  'player_error_audio_focus_denied': '其他应用正在使用音频，暂时无法播放。',
  'player_error_local_file_missing': '找不到“{title}”的本地文件。',
  'player_error_open_local_file': '无法打开“{title}”的本地文件。',
  'player_error_open_next_preserved_current': '无法播放下一首“{title}”，当前歌曲继续播放。',
  'player_error_current_removed_from_library': '当前歌曲已从曲库移除，播放已停止。',
};

const _traditional = <String, String>{
  '设置': '設定',
  '外观与播放器': '外觀與播放器',
  '账号与云同步': '帳號與雲端同步',
  '登录、头像与跨设备同步': '登入、頭像與跨裝置同步',
  '语言': '語言',
  '语言与显示文字': '語言與顯示文字',
  '存储与数据': '儲存與資料',
  '此设备': '此裝置',
  '此设备数据库': '此裝置資料庫',
  '关于': '關於',
  '返回设置': '返回設定',
  '首页': '首頁',
  '曲库': '曲庫',
  '本地曲库': '本機曲庫',
  '歌单': '歌單',
  '我的歌单': '我的歌單',
  '我的收藏': '我的收藏',
  '最近播放': '最近播放',
  'MV 专区': 'MV 專區',
  '听歌排行': '聆聽排行',
  '我的音乐': '我的音樂',
  '常用歌单': '常用歌單',
  '选择常用歌单': '選擇常用歌單',
  '折叠': '收合',
  '展开': '展開',
  '切换皮肤': '切換皮膚',
  '播放器背景': '播放器背景',
  '选择一套皮肤，也可以导入并裁切自己的图片。': '選擇一套皮膚，也可以匯入並裁切自己的圖片。',
  '音频声纹识别': '音訊聲紋辨識',
  '全面识别': '全面辨識',
  '全面识别整个曲库': '全面辨識整個曲庫',
  '配置免费音频声纹': '設定免費音訊聲紋',
  '在 acoustid.org 注册一个非商业应用即可免费获得 Application API Key。这里只保存应用 Key，不需要账户密码。': '在 acoustid.org 註冊一個非商業應用，即可免費取得 Application API Key。這裡只會儲存應用 Key，不需要帳戶密碼。',
  '清除 Key': '清除 Key',
  '这个 Application API Key 格式不正确。': '這個 Application API Key 格式不正確。',
  '已关闭声纹联网查询': '已關閉聲紋網路查詢',
  '音频声纹已启用': '音訊聲紋已啟用',
  '正在停止，请稍候…': '正在停止，請稍候…',
  '正在识别第 {current} / {total} 首': '正在辨識第 {current} / {total} 首',
  '即将完成': '即將完成',
  '已找到 {count} 条可预览的建议': '已找到 {count} 條可預覽的建議',
  '停止扫描': '停止掃描',
  '整理预览 · 已选 {count} 首': '整理預覽 · 已選 {count} 首',
  '原信息': '原資訊',
  '可信度': '可信度',
  '全不选': '全部取消',
  '应用 {count} 项': '套用 {count} 項',
  '正在读取数据库位置…': '正在讀取資料庫位置…',
  '动态特效与性能': '動態特效與效能',
  '可随设备性能切换特效强度；关闭动态特效不会改变壁纸和主题配色。': '可依裝置效能切換特效強度；關閉動態特效不會改變桌布和主題配色。',
  '完整特效': '完整特效',
  '保留完整环境动画、玻璃模糊和过渡效果': '保留完整環境動畫、玻璃模糊和轉場效果',
  '节能特效': '節能特效',
  '降低动画帧率、粒子数量和图片缓存占用': '降低動畫幀率、粒子數量和圖片快取用量',
  '关闭动态特效': '關閉動態特效',
  '保留静态主题，停用环境动画和实时液态毛玻璃模糊': '保留靜態主題，停用環境動畫和即時液態毛玻璃模糊',
  '版本': '版本',
  '构建': '建置',
  '检查更新': '檢查更新',
  '正在检查…': '正在檢查…',
  '产品网站': '產品網站',
  '当前已是最新版本。': '目前已是最新版本。',
  '暂时无法检查更新，请确认网络后重试。': '暫時無法檢查更新，請確認網路後重試。',
  '无法打开链接，请稍后重试。': '無法開啟連結，請稍後再試。',
  '发现新版本': '發現新版本',
  '当前版本': '目前版本',
  '将打开发布页面，由你选择安装包。': '將開啟發佈頁面，由你選擇安裝套件。',
  '将打开当前设备对应的安装包下载。': '將開啟目前裝置對應的安裝套件下載。',
  '稍后再说': '稍後再說',
  '查看发布页': '查看發佈頁',
  '打开下载': '開啟下載',
  '完整备份与恢复': '完整備份與還原',
  '数据库、歌曲、MV、封面、自定义壁纸和本地设置会放进同一个可校验备份。': '資料庫、歌曲、MV、封面、自訂桌布和本機設定會放進同一個可驗證備份。',
  '内部自动备份会随卸载或清除数据一起删除；跨设备或换签名前请导出完整备份到外部位置。':
      '內部自動備份會隨解除安裝或清除資料一併刪除；跨裝置或更換簽章前，請將完整備份匯出至外部位置。',
  '轻量自动快照已开启；保存数据库和封面，不重复复制歌曲与 MV，默认保留最新 3 份。':
      '輕量自動快照已開啟；儲存資料庫和封面，不重複複製歌曲與 MV，預設保留最新 3 份。',
  '自动备份': '自動備份',
  '最近': '最近',
  '导出完整备份': '匯出完整備份',
  '从备份恢复': '從備份還原',
  '恢复当前设备快照': '還原目前裝置快照',
  '恢复当前设备快照？': '還原目前裝置快照？',
  '这会恢复最近一次自动保存的曲库数据库和托管图片。歌曲与 MV 不会从快照复制；只有当前设备上仍存在的媒体路径会被保留。Sona 会先完整校验，并在下次冷启动时应用。': '這會還原最近一次自動儲存的曲庫資料庫和託管圖片。歌曲與 MV 不會從快照複製；只有目前裝置上仍存在的媒體路徑會被保留。Sona 會先完整驗證，並在下次冷啟動時套用。',
  '校验并恢复': '驗證並還原',
  '自动快照损坏或所需本机媒体已不存在。当前曲库没有被修改。': '自動快照已損壞或所需的本機媒體已不存在。目前曲庫未被修改。',
  '刷新自动备份状态': '重新整理自動備份狀態',
  '处理中…': '處理中…',
  '选择完整备份保存位置': '選擇完整備份儲存位置',
  '创建完整备份失败，请稍后重试。': '建立完整備份失敗，請稍後再試。',
  '完整备份已创建': '完整備份已建立',
  '备份已创建，但有文件缺失': '備份已建立，但有檔案缺失',
  '文件': '檔案',
  '条目': '項目',
  '大小': '大小',
  '缺失引用': '缺失參照',
  '请将外部备份妥善保管；它可能包含歌曲、MV、封面和本地设置，且当前未加密。':
      '請妥善保管外部備份；其中可能包含歌曲、MV、封面和本機設定，且目前未加密。',
  '完成': '完成',
  '从完整备份恢复？': '從完整備份還原？',
  'Sona 会先完整校验备份，在下次冷启动时替换曲库数据库并保留一份恢复前数据库。当前播放将在退出时停止。':
      'Sona 會先完整驗證備份，在下次冷啟動時替換曲庫資料庫，並保留一份還原前資料庫。目前播放會在退出時停止。',
  '选择备份并校验': '選擇備份並驗證',
  '选择 Sona 完整备份': '選擇 Sona 完整備份',
  '备份校验或恢复准备失败。当前曲库没有被修改。': '備份驗證或還原準備失敗。目前曲庫未被修改。',
  '备份校验通过': '備份驗證通過',
  '备份版本': '備份版本',
  '恢复已安全排队。退出并重新打开 Sona 后生效。': '還原已安全排程。退出並重新開啟 Sona 後生效。',
  '取消此次恢复': '取消此次還原',
  '稍后退出': '稍後退出',
  '立即退出 Sona': '立即退出 Sona',
  '已取消此次恢复。': '已取消此次還原。',
  '有待处理的恢复': '有待處理的還原',
  '恢复已排队，退出并重新打开 Sona 后应用。你可以在此取消。': '還原已排程，退出並重新開啟 Sona 後套用。你可以在此取消。',
  '上次恢复未能安全应用': '上次還原未能安全套用',
  'Sona 已保留原曲库，下一次启动会再次尝试。你也可以取消这个恢复任务。': 'Sona 已保留原曲庫，下次啟動會再次嘗試。你也可以取消這個還原任務。',
  '恢复任务已取消，当前曲库未被修改。': '還原任務已取消，目前曲庫未被修改。',
  '取消恢复任务失败，请稍后重试。': '取消還原任務失敗，請稍後再試。',
  'Sona 用户': 'Sona 使用者',
  '本地模式': '本機模式',
  '前往设置连接云账号': '前往設定連接雲端帳號',
  '本地音乐空间': '本機音樂空間',
  '正在分析 {file}': '正在分析 {file}',
  'library_read_failed': '讀取本機曲庫失敗，請重新開啟 Sona 後再試。',
  'track_not_persisted': '這首歌曲尚未儲存，無法辨識。',
  'identification_in_progress': '正在辨識這首歌曲，請稍候。',
  'identification_file_missing': '找不到本機檔案，無法辨識。',
  'identification_fingerprint_match': '已透過音訊聲紋找到相符結果。',
  'identification_catalog_fallback_after_fingerprint': '聲紋沒有可靠命中，已用公開曲庫完成後備校準。',
  'identification_catalog_fallback': '已用檔案資訊和公開曲庫完成後備校準。',
  'identification_source_local_cleanup': '本機智慧清理',
  'identification_local_cleanup_explanation':
      '公開曲庫沒有可靠結果，僅根據標籤和檔名提供建議，請確認後再套用。',
  'identification_local_cleanup_suggested': '沒有查到可靠的網路結果，已產生本機清理建議。',
  'identification_no_reliable_result': '沒有找到可靠的辨識結果，已保留原資訊。',
  'identification_source_acoustid': 'AcoustID 音訊聲紋',
  'identification_acoustid_explanation': '根據音訊內容配對，與檔名無關。',
  'identification_source_musicbrainz': 'MusicBrainz 公開曲庫',
  'identification_musicbrainz_explanation': '根據清理後的曲名、歌手和時長進行網路校準，並非聲紋命中。',
  'manual_edit': '手動編輯',
  'cover_file_missing': '找不到選取的封面檔案。',
  'cover_file_type_unsupported': '請選擇 JPG、PNG 或 WebP 圖片。',
  'cover_file_too_large': '封面圖片不能超過 12 MB。',
  'audio_file_required': '請先選擇音訊檔案。',
  'audio_already_in_library': '這個音訊檔案已在曲庫中。',
  'unexpected_library_error': '操作未完成，請稍後再試。',
  'account_username_invalid': '請輸入有效的帳號名稱。',
  'account_sign_in_incomplete': '登入未完成，請重試。',
  'account_sign_in_success': '登入成功，正在檢查雲端資料。',
  'account_username_format_invalid': '帳號名稱格式不正確。',
  'account_sign_up_incomplete': '帳號建立未完成，請確認雲端已關閉電子郵件驗證後重試。',
  'account_sign_up_success': '帳號建立成功，已登入。',
  'account_signed_out': '已登出雲端帳號，本機音樂不受影響。',
  'account_display_name_synced': '顯示名稱已同步。',
  'account_avatar_uploading': '正在上傳頭像…',
  'account_avatar_updated': '頭像更新成功，登入其他裝置後會自動還原。',
  'account_cloud_not_configured': '雲端尚未設定。',
  'account_sign_up_disabled': '雲端註冊入口尚未開啟，請稍後重試。',
  'account_invalid_credentials': '帳號名稱或密碼不正確。',
  'account_username_taken': '這個帳號名稱已被使用，請更換帳號名稱。',
  'account_service_unavailable': '帳號服務暫時無法完成操作，請稍後重試。',
  'account_avatar_save_failed': '頭像暫時無法儲存到雲端，請稍後重試。',
  'account_profile_update_failed': '雲端資料暫時無法更新，帳號仍保持登入，請稍後重試。',
  'account_operation_failed': '操作未完成，請稍後重試。',
  '还没有配对唱片': '還沒有配對唱片',
  '暂停': '暫停',
  '播放': '播放',
  '播放进度': '播放進度',
  '正在准备 MV 画面': '正在準備 MV 畫面',
  'MV 画面准备超时，音频仍在播放': 'MV 畫面準備逾時，音訊仍在播放',
  'MV 画面暂时不可用，音频仍在播放': 'MV 畫面暫時無法使用，音訊仍在播放',
  'MV 已与这首歌配对。': 'MV 已與這首歌配對。',
  '唱片音频已与这支 MV 配对。': '唱片音訊已與這支 MV 配對。',
  '音频配对失败，请确认文件可用。': '音訊配對失敗，請確認檔案可用。',
  '请选择音频文件。': '請選擇音訊檔案。',
  '这首音频已经在曲库中。': '這首音訊已經在曲庫中。',
  '多套明亮皮肤，也可以导入并裁切自己的图片。': '多套明亮皮膚，也可以匯入並裁切自己的圖片。',
  '替换视频文件': '取代影片檔案',
  '更换关联 MV': '更換關聯 MV',
  '关联一个 MV': '關聯一支 MV',
  '解除 MV 配对': '解除 MV 配對',
  '播放器设置': '播放器設定',
  '睡眠定时、后台播放状态': '睡眠定時、背景播放狀態',
  '睡眠定时会在时间到后暂停当前播放。': '睡眠定時會在時間到後暫停目前播放。',
  '将在 {duration} 后暂停播放。': '將在 {duration} 後暫停播放。',
  '{minutes} 分钟': '{minutes} 分鐘',
  '自定义': '自訂',
  '关闭定时': '關閉定時',
  '后台播放与系统通知': '背景播放與系統通知',
  'Android 已接入系统媒体服务：支持后台播放、通知栏、耳机与锁屏控制。':
      'Android 已接入系統媒體服務：支援背景播放、通知列、耳機與鎖定畫面控制。',
  '自定义定时': '自訂定時',
  '暂停前播放时长（分钟）': '暫停前播放時長（分鐘）',
  '例如 90': '例如 90',
  '可设 1–720 分钟': '可設 1–720 分鐘',
  '请输入 1 到 720 之间的分钟数': '請輸入 1 到 720 之間的分鐘數',
  '开始定时': '開始定時',
  '最小化': '最小化',
  '最大化或还原': '最大化或還原',
  '切换到唱片播放': '切換到唱片播放',
  '播放队列': '播放佇列',
  '关闭播放队列': '關閉播放佇列',
  '{source} · {count} 首': '{source} · {count} 首',
  '来自：{source} · {count} 首': '來自：{source} · {count} 首',
  '唱片': '唱片',
  'MV · 已配对': 'MV · 已配對',
  '关联 MV': '關聯 MV',
  '还没有配对 MV': '還沒有配對 MV',
  '导入歌曲 / MV': '匯入歌曲 / MV',
  '导入': '匯入',
  '导入第一首歌 / MV': '匯入第一首歌曲 / MV',
  '导入第一首音乐，开始建立你的私人曲库。': '匯入第一首音樂，開始建立你的私人曲庫。',
  '把电脑里的 MP3 或 MP4/MV 导进来，建立你的音乐库。': '將電腦裡的 MP3 或 MP4/MV 匯入，建立你的音樂庫。',
  '导入自己的背景': '匯入自己的背景',
  '我的背景 {index}': '我的背景 {index}',
  '裁切播放器背景': '裁切播放器背景',
  '裁切图片': '裁切圖片',
  '拖动图片调整位置，双指或滚轮缩放': '拖動圖片調整位置，雙指或滾輪縮放',
  '裁切失败：{cause}': '裁切失敗：{cause}',
  '已锁定当前播放器比例 {ratio} : 1': '已鎖定目前播放器比例 {ratio} : 1',
  '处理中': '處理中',
  '使用这一区域': '使用這個區域',
  '列表循环': '列表循環',
  '单曲循环': '單曲循環',
  '随机播放': '隨機播放',
  'cloud_sign_in_required': '請先登入雲端帳號。',
  'cloud_track_recycled': '已將「{title}」移入雲端回收站。',
  'cloud_track_restored': '已還原「{title}」。',
  'cloud_sync_planning': '正在整理同步計畫…',
  'cloud_sync_preview': '待上傳 {upload} 首、待下載 {download} 首、雲端歌單待還原 {playlistDownload} 個；{unchanged} 首無需變更。',
  'cloud_sync_preview_with_skipped': '待上傳 {upload} 首、待下載 {download} 首、雲端歌單待還原 {playlistDownload} 個；{unchanged} 首無需變更。另有 {tooLarge} 首超過 50 MB，仍只保留在本機。',
  'cloud_sync_connecting': '正在連接雲端…',
  'cloud_syncing_track': '正在同步「{title}」…',
  'cloud_syncing_rankings': '正在同步聆聽排行…',
  'cloud_syncing_playlists': '正在同步歌單…',
  'cloud_sync_downloading_tracks': '正在下載雲端曲目…',
  'cloud_sync_restoring_playlists': '正在還原雲端歌單…',
  'cloud_sync_complete': '同步完成',
  'cloud_sync_complete_changes': '同步完成：上傳 {uploaded} 首，下載 {downloaded} 首。',
  'cloud_sync_complete_changes_with_skipped': '同步完成：上傳 {uploaded} 首，下載 {downloaded} 首；{skippedLarge} 首超過 50 MB，仍只保留在本機。',
  'cloud_sync_complete_unchanged': '同步完成：本機與雲端已經一致。',
  'cloud_sync_complete_unchanged_with_skipped':
      '同步完成：本機與雲端已經一致；{skippedLarge} 首超過 50 MB，仍只保留在本機。',
  'cloud_sync_interrupted': '同步已中斷，本機曲庫不受影響。',
  'cloud_error_offline': '離線狀態，無法連接雲端。',
  'cloud_error_invalid_credentials': '雲端帳號登入狀態已失效，請重新登入。',
  'cloud_error_permission': '雲端拒絕了這次操作，請檢查帳號權限。',
  'cloud_error_connection': '暫時無法連接雲端，請稍後再試。',
  'cloud_error_schema': '雲端資料結構尚未完成設定。',
  'cloud_error_media': '雲端媒體檔案暫時無法使用，請稍後再試。',
  'cloud_error_generic': '雲端同步暫時無法完成，請稍後再試。',
  'queue_source_local_library': '本機曲庫',
  'queue_source_search': '搜尋「{query}」',
  'queue_source_favorites': '我的收藏',
  'queue_source_videos': '有 MV',
  'queue_source_recent': '最近播放',
  'queue_source_rankings': '聽歌排行',
  'queue_source_cloud_library': '雲端資料庫',
  'queue_source_playlist': '播放清單「{playlist}」',
  'player_error_engine': '播放器發生錯誤，請重試。',
  'player_error_open_track_preserved_previous': '無法播放「{title}」，已繼續保留上一首歌曲。',
  'player_error_audio_focus_denied': '其他應用程式正在使用音訊，暫時無法播放。',
  'player_error_local_file_missing': '找不到「{title}」的本機檔案。',
  'player_error_open_local_file': '無法開啟「{title}」的本機檔案。',
  'player_error_open_next_preserved_current': '無法播放下一首「{title}」，目前歌曲會繼續播放。',
  'player_error_current_removed_from_library': '目前歌曲已從曲庫移除，播放已停止。',
};

const _english = <String, String>{
  '设置': 'Settings',
  '外观与播放器': 'Appearance & player',
  '账号与云同步': 'Account & cloud sync',
  '登录、头像与跨设备同步': 'Sign in, profile and device sync',
  '语言': 'Languages',
  '语言与显示文字': 'Language and display text',
  '简体中文': 'Simplified Chinese',
  '繁體中文': 'Traditional Chinese',
  '英文': 'English',
  '选择界面语言': 'Choose interface language',
  '切换后立即应用，并在下次启动时保留。':
      'Changes apply immediately and are kept for the next launch.',
  '当前语言': 'Current language',
  '存储与数据': 'Storage & data',
  '此设备': 'this device',
  '关于': 'About',
  '返回设置': 'Back to Settings',
  '此设备数据库': 'On-device database',
  '正在读取数据库位置…': 'Reading database location…',
  '动态特效与性能': 'Visual effects & performance',
  '可随设备性能切换特效强度；关闭动态特效不会改变壁纸和主题配色。': 'Match effects to your device. Turning motion off keeps your wallpaper and theme colors.',
  '完整特效': 'Full effects',
  '保留完整环境动画、玻璃模糊和过渡效果': 'Full ambient motion, glass blur and transitions',
  '节能特效': 'Energy saver',
  '降低动画帧率、粒子数量和图片缓存占用': 'Lower frame rate, particle count and image-cache use',
  '关闭动态特效': 'Motion off',
  '保留静态主题，停用环境动画和实时液态毛玻璃模糊': 'Keep the static theme, and disable ambient motion and real-time liquid-glass blur',
  '版本': 'Version',
  '构建': 'build',
  '检查更新': 'Check for updates',
  '正在检查…': 'Checking…',
  '产品网站': 'Website',
  '当前已是最新版本。': 'You already have the latest version.',
  '暂时无法检查更新，请确认网络后重试。':
      'Could not check for updates. Check your connection and try again.',
  '无法打开链接，请稍后重试。': 'Could not open the link. Try again later.',
  '发现新版本': 'New version available',
  '当前版本': 'Current version',
  '将打开发布页面，由你选择安装包。':
      'The release page will open so you can choose an installer.',
  '将打开当前设备对应的安装包下载。':
      'The installer for this device will open in your browser.',
  '稍后再说': 'Later',
  '查看发布页': 'View release',
  '打开下载': 'Open download',
  '完整备份与恢复': 'Complete backup & restore',
  '数据库、歌曲、MV、封面、自定义壁纸和本地设置会放进同一个可校验备份。': 'Database, songs, MVs, covers, custom wallpapers and local settings are stored in one verifiable backup.',
  '内部自动备份会随卸载或清除数据一起删除；跨设备或换签名前请导出完整备份到外部位置。': 'Internal automatic backups are removed when the app is uninstalled or its data is cleared. Export a complete backup externally before moving devices or changing signatures.',
  '轻量自动快照已开启；保存数据库和封面，不重复复制歌曲与 MV，默认保留最新 3 份。': 'Lightweight automatic snapshots are on. They save the database and artwork without duplicating songs or MVs, and keep the latest 3 copies.',
  '自动备份': 'Automatic backups',
  '最近': 'Latest',
  '导出完整备份': 'Export complete backup',
  '从备份恢复': 'Restore from backup',
  '恢复当前设备快照': 'Restore on-device snapshot',
  '恢复当前设备快照？': 'Restore the latest on-device snapshot?',
  '这会恢复最近一次自动保存的曲库数据库和托管图片。歌曲与 MV 不会从快照复制；只有当前设备上仍存在的媒体路径会被保留。Sona 会先完整校验，并在下次冷启动时应用。': 'This restores the latest automatically saved library database and managed images. Songs and MVs are not copied from the snapshot; only media paths that still exist on this device are preserved. Sona verifies everything first and applies it at the next cold start.',
  '校验并恢复': 'Verify and restore',
  '自动快照损坏或所需本机媒体已不存在。当前曲库没有被修改。': 'The automatic snapshot is damaged or required on-device media is missing. The current library was not changed.',
  '刷新自动备份状态': 'Refresh automatic backup status',
  '处理中…': 'Working…',
  '选择完整备份保存位置': 'Choose a location for the complete backup',
  '创建完整备份失败，请稍后重试。': 'Could not create the complete backup. Try again later.',
  '完整备份已创建': 'Complete backup created',
  '备份已创建，但有文件缺失': 'Backup created with missing files',
  '文件': 'File',
  '条目': 'Entries',
  '大小': 'Size',
  '缺失引用': 'Missing references',
  '请将外部备份妥善保管；它可能包含歌曲、MV、封面和本地设置，且当前未加密。': 'Keep this external backup safe. It may contain songs, MVs, covers and local settings, and is not currently encrypted.',
  '完成': 'Done',
  '从完整备份恢复？': 'Restore from a complete backup?',
  'Sona 会先完整校验备份，在下次冷启动时替换曲库数据库并保留一份恢复前数据库。当前播放将在退出时停止。': 'Sona will fully verify the backup, replace the library database on the next cold start, and keep a pre-restore database. Current playback will stop when you exit.',
  '选择备份并校验': 'Choose and verify backup',
  '选择 Sona 完整备份': 'Choose a Sona complete backup',
  '备份校验或恢复准备失败。当前曲库没有被修改。': 'Backup verification or restore preparation failed. The current library was not changed.',
  '备份校验通过': 'Backup verified',
  '备份版本': 'Backup version',
  '恢复已安全排队。退出并重新打开 Sona 后生效。':
      'The restore is safely queued. Exit and reopen Sona to apply it.',
  '取消此次恢复': 'Cancel this restore',
  '稍后退出': 'Exit later',
  '立即退出 Sona': 'Exit Sona now',
  '已取消此次恢复。': 'This restore was cancelled.',
  '有待处理的恢复': 'Restore pending',
  '恢复已排队，退出并重新打开 Sona 后应用。你可以在此取消。': 'The restore is queued and will apply after you exit and reopen Sona. You can cancel it here.',
  '上次恢复未能安全应用': 'The last restore could not be applied safely',
  'Sona 已保留原曲库，下一次启动会再次尝试。你也可以取消这个恢复任务。': 'Sona kept the original library and will try again at the next launch. You can also cancel this restore.',
  '恢复任务已取消，当前曲库未被修改。':
      'The restore was cancelled. The current library was not changed.',
  '取消恢复任务失败，请稍后重试。': 'Could not cancel the restore. Try again later.',
  '音频声纹识别': 'Audio fingerprint recognition',
  '全面识别': 'Identify all',
  '全面识别整个曲库': 'Identify the full library',
  '配置免费音频声纹': 'Configure free audio fingerprinting',
  '在 acoustid.org 注册一个非商业应用即可免费获得 Application API Key。这里只保存应用 Key，不需要账户密码。': 'Register a non-commercial app at acoustid.org to get a free Application API Key. Sona stores only the app key and never needs your account password.',
  '清除 Key': 'Clear key',
  '这个 Application API Key 格式不正确。':
      'This Application API Key has an invalid format.',
  '已关闭声纹联网查询': 'Online fingerprint lookup is off',
  '音频声纹已启用': 'Audio fingerprinting is enabled',
  '切换皮肤': 'Change theme',
  '播放器背景': 'Player background',
  '选择一套皮肤，也可以导入并裁切自己的图片。': 'Choose a theme, or import and crop your own image.',
  '曲库里没有可识别的歌曲。': 'There are no tracks to identify.',
  '将逐首扫描曲库中的 {count} 首歌曲。Windows 且已配置 AcoustID 时优先使用音频声纹；其他情况使用标签、文件名和免费公开曲库。所有建议都会先预览，确认后才修改曲库。\n\n公开曲库限制为每秒最多 1 次请求，歌曲较多时会花更长时间。': 'Sona will scan all {count} tracks one by one. On Windows with AcoustID configured, audio fingerprints are tried first; otherwise Sona uses tags, filenames and the free public catalog. Every suggestion is previewed before your library changes.\n\nThe public catalog allows at most one request per second, so larger libraries take longer.',
  '暂不扫描': 'Not now',
  '开始全面识别': 'Identify all',
  '没有发现需要修改的歌曲信息。': 'No metadata changes were found.',
  '已完成 {count} 首歌曲的信息校准。': 'Corrected metadata for {count} tracks.',
  '正在全面识别': 'Identifying full library',
  '正在停止，请稍候…': 'Stopping…',
  '正在识别第 {current} / {total} 首': 'Identifying track {current} of {total}',
  '即将完成': 'Finishing…',
  '已找到 {count} 条可预览的建议': '{count} suggestions ready to preview',
  '停止扫描': 'Stop scan',
  '整理预览 · 已选 {count} 首': 'Review changes · {count} selected',
  '原信息': 'Original',
  '全不选': 'Select none',
  '应用 {count} 项': 'Apply {count}',
  '未配置时仍可使用标签、文件名和 MusicBrainz 后备校准':
      'Tags, filenames and MusicBrainz remain available without a key',
  'AcoustID 已配置 · 声纹不命中时自动回退公开曲库':
      'AcoustID configured · falls back to the public catalog when needed',
  '配置免费 Key': 'Configure free key',
  '已启用': 'Enabled',
  '首页': 'Home',
  '曲库': 'Library',
  '本地曲库': 'Local library',
  '歌单': 'Playlists',
  '我的收藏': 'Favorites',
  '最近播放': 'Recently played',
  'MV 专区': 'Music videos',
  '听歌排行': 'Listening stats',
  '我的音乐': 'My music',
  '常用歌单': 'Pinned playlists',
  '选择常用歌单': 'Choose pinned playlists',
  '取消': 'Cancel',
  '保存': 'Save',
  '折叠': 'Collapse',
  '展开': 'Expand',
  '首': ' tracks',
  '我的背景': 'My background',
  '只属于你的音乐空间': 'Your personal music space',
  '导入音乐': 'Import music',
  '本地歌曲': 'Local tracks',
  '已配对 MV': 'Paired videos',
  '个': 'items',
  'AI 识别歌曲信息': 'Identify song information',
  '编辑歌曲信息与封面': 'Edit song information & cover',
  '识别与编辑历史': 'Identification & edit history',
  '编辑歌曲信息': 'Edit song information',
  '歌曲封面': 'Song cover',
  '图片会复制到 Sona 的托管目录，移动原图不会影响封面。清除后自动回退到文字封面。': 'The image is copied into Sona-managed storage, so moving the original will not break the cover. Clearing it restores the text cover.',
  '选择图片': 'Choose image',
  '使用文字封面': 'Use text cover',
  '歌名': 'Song title',
  '专辑（可留空）': 'Album (optional)',
  '歌名和歌手不能为空。': 'Song title and artist are required.',
  '歌曲信息已保存，可随时从历史中撤销。':
      'Song information saved. You can undo it from history at any time.',
  '保存失败': 'Could not save',
  '这首歌还没有识别或手动编辑记录。':
      'This song has no identification or manual edit history yet.',
  '无法撤销：歌曲信息已被其他操作修改，请重新打开历史。': 'Cannot undo because another action changed this song. Reopen its history and try again.',
  '已撤销最近一次校准，恢复为': 'Undid the latest correction and restored ',
  '已撤销': 'Undone',
  '撤销最近一次': 'Undo latest change',
  '清除封面': 'Cover cleared',
  '更新封面': 'Cover updated',
  '手动编辑': 'Manual edit',
  '取消收藏': 'Remove from favorites',
  '收藏': 'Favorite',
  '加入歌单': 'Add to playlist',
  '从最近播放中移除': 'Remove from recently played',
  '从听歌排行中移除': 'Remove from listening stats',
  '从歌单中移除': 'Remove from playlist',
  '从本地曲库移除': 'Remove from local library',
  '从本地曲库移除？': 'Remove from local library?',
  '移除': 'Remove',
  '正在分析标签、文件名和公开曲库…': 'Analyzing tags, filename and public catalogs…',
  '识别结果': 'Identification result',
  '歌曲': 'Song',
  '歌手': 'Artist',
  '专辑': 'Album',
  '未提供': 'Not provided',
  '保留原信息': 'Keep original',
  '应用校准': 'Apply correction',
  '未标注专辑': 'Album not specified',
  '从云端删除': 'Delete from cloud',
  '批量管理': 'Batch manage',
  '全选': 'Select all',
  '取消全选': 'Clear selection',
  '全选全部云端歌曲': 'Select every cloud track',
  '退出批量管理': 'Exit batch mode',
  '删除': 'Delete',
  '正在删除 {completed} / {total} 首': 'Deleting {completed} / {total} tracks',
  '已选 {selected} / {total} 首': 'Selected {selected} / {total} tracks',
  '删除选中的 {count} 首云端歌曲？': 'Delete {count} selected cloud tracks?',
  '删除 {count} 首云副本': 'Delete {count} cloud copies',
  '移入云端回收站？': 'Move to cloud recycle bin?',
  '移入回收站': 'Move to recycle bin',
  '移入回收站（{count}）': 'Move to recycle bin ({count})',
  '“{title}”会移入云端回收站，30 天内可以恢复。\n\n本机文件不会删除；回收站中的歌曲不会被自动重新上传。': '“{title}” will move to the cloud recycle bin and can be restored for 30 days.\n\nThe local file will not be deleted, and recycled tracks will not be uploaded again automatically.',
  '这些歌曲会移入云端回收站，30 天内可以恢复。\n\n本机文件不会删除；回收站中的歌曲不会被自动重新上传。': 'These tracks will move to the cloud recycle bin and can be restored for 30 days.\n\nLocal files will not be deleted, and recycled tracks will not be uploaded again automatically.',
  '已将“{title}”移入云端回收站。': 'Moved “{title}” to the cloud recycle bin.',
  '已将 {removed} 首歌曲移入云端回收站。':
      'Moved {removed} tracks to the cloud recycle bin.',
  '已恢复 {count} 首云端歌曲。': 'Restored {count} cloud tracks.',
  '撤销': 'Undo',
  '云端回收站': 'Cloud recycle bin',
  '回收站 {count}': 'Recycle bin {count}',
  '{count} 首 · 删除后保留 30 天':
      '{count} tracks · retained for 30 days after deletion',
  '回收站是空的。': 'The recycle bin is empty.',
  '恢复': 'Restore',
  '剩余 {days} 天': '{days} days remaining',
  '清空': 'Empty',
  '清理中…': 'Emptying…',
  '永久删除': 'Delete permanently',
  '永久删除云端文件？': 'Permanently delete cloud file?',
  '“{title}”的云端记录和云端媒体文件会被永久删除，无法恢复。本机文件不受影响。': 'The cloud record and cloud media for “{title}” will be permanently deleted and cannot be restored. The local file is unaffected.',
  '清空云端回收站？': 'Empty the cloud recycle bin?',
  '{count} 首歌曲的云端文件会被永久删除，此操作无法撤销。': 'Cloud files for {count} tracks will be permanently deleted. This cannot be undone.',
  '永久清空': 'Empty permanently',
  '关闭': 'Close',
  '这些歌曲会从云空间和其他设备可同步内容中移除。\n\n本机文件不会删除；此后它们也不会被自动重新上传。此操作无法撤销。': 'These tracks will be removed from cloud storage and from content available to sync on other devices.\n\nLocal files will not be deleted, and these tracks will not be uploaded again automatically. This cannot be undone.',
  '已从云端删除 {removed} 首歌曲，本机文件保持不变。':
      'Removed {removed} tracks from the cloud. Local files are unchanged.',
  '已删除 {removed} 首，{failed} 首未能删除，请稍后重试。': 'Removed {removed} tracks. {failed} could not be deleted; please try again later.',
  '最近同步': 'Recently synced',
  '曲名 A–Z': 'Title A–Z',
  '歌手 A–Z': 'Artist A–Z',
  '专辑 A–Z': 'Album A–Z',
  '文件大小': 'File size',
  '可信度': 'Confidence',
  '将不再显示在 Sona 中，电脑里的原始文件不会被删除。': ' will no longer appear in Sona. The original file on this computer will not be deleted.',
  'AcoustID 音频声纹': 'AcoustID audio fingerprint',
  'MusicBrainz 公开曲库': 'MusicBrainz public catalog',
  '本地智能清洗': 'Local metadata cleanup',
  '根据音频内容匹配，与文件名无关。':
      'Matched from audio content independently of the filename.',
  '根据清洗后的曲名、歌手和时长进行联网校准，并非声纹命中。':
      'Matched online using the cleaned title, artist and duration.',
  '还没有播放歌曲': 'Nothing playing yet',
  '当前没有歌曲': 'No song is selected',
  '从曲库选择一首歌': 'Choose a song from your library',
  '从曲库中选择一首歌': 'Choose a song from your library',
  '从曲库中选择一首歌，播放控制会出现在这里。':
      'Choose a song from your library to show playback controls here.',
  '去曲库': 'Open library',
  '上一首': 'Previous',
  '下一首': 'Next',
  '播放队列': 'Play queue',
  'Sona 用户': 'Sona user',
  '本地模式': 'Local mode',
  '前往设置连接云账号': 'Open Settings to connect a cloud account',
  '本地音乐空间': 'Local music space',
  '正在分析 {file}': 'Analyzing {file}',
  '未知歌手': 'Unknown artist',
  '未标注歌手': 'Artist not specified',
  '未知专辑': 'Unknown album',
  '本地视频': 'Local video',
  '独立 MV': 'Standalone video',
  '云账号框架已就绪': 'Cloud account support is ready',
  '等待连接 Supabase 项目。连接后先同步账号、头像、歌单、收藏、播放统计和设置；歌曲文件稍后单独启用。': 'Connect a Supabase project to sync accounts, profiles, playlists, favorites, listening stats and settings. Media-file sync can be enabled separately.',
  '等待密钥': 'Awaiting credentials',
  '管理头像、名称和当前登录账号。':
      'Manage your profile picture, display name and signed-in account.',
  '已连接': 'Connected',
  '更换头像': 'Change picture',
  '修改名称': 'Change name',
  '退出账号': 'Sign out',
  '云同步': 'Cloud sync',
  '离线状态，无法连接至云端。本地曲库和播放不受影响。': 'You are offline and cannot reach the cloud. Your local library and playback are unaffected.',
  '查看同步预览、同步状态，并管理云端保存的歌曲。':
      'Review the sync plan and status, and manage tracks saved in the cloud.',
  '离线': 'Offline',
  '同步中': 'Syncing',
  '云空间': 'Cloud space',
  '同步预览': 'Sync preview',
  '立即同步': 'Sync now',
  '登录 Sona 云账号': 'Sign in to Sona Cloud',
  '使用账号名和密码登录；同一账号可同步头像、收藏、歌单、播放记录和音乐数据。': 'Sign in with a username and password to sync your profile, favorites, playlists, listening history and music data.',
  '你的收藏、歌单、播放记录和小于 50 MB 的音乐可在已登录设备间同步；本地原文件仍保留在本机。': 'Favorites, playlists, listening history and music files under 50 MB can sync between signed-in devices. Original local files remain on this device.',
  '未登录': 'Signed out',
  '登录': 'Sign in',
  '注册': 'Create account',
  '裁切头像': 'Crop profile picture',
  '拖动图片并缩放，保留想展示的正方形区域。':
      'Drag and zoom the image to frame the square area you want to show.',
  '注册 Sona': 'Create a Sona account',
  '登录 Sona': 'Sign in to Sona',
  '账号名': 'Username',
  '3–24 位：字母、数字或下划线；以字母开头':
      '3–24 letters, numbers or underscores; start with a letter',
  '显示名称（可选）': 'Display name (optional)',
  '显示名称': 'Display name',
  '密码': 'Password',
  '至少 8 位': 'At least 8 characters',
  '隐藏密码': 'Hide password',
  '显示密码': 'Show password',
  '确认密码': 'Confirm password',
  '请再输入一次密码': 'Enter the password again',
  '账号名格式不正确，密码至少 8 位。':
      'Check the username format and use a password of at least 8 characters.',
  '请输入正确的账号名，密码至少 8 位。':
      'Enter a valid username and a password of at least 8 characters.',
  '两次输入的密码不一致，请重新确认。': 'The passwords do not match. Please confirm them again.',
  '账号创建成功，已登录。': 'Your account was created and signed in.',
  '登录成功。': 'Signed in.',
  '操作未完成，请重试。': 'The operation did not complete. Please try again.',
  '创建账号': 'Create account',
  '修改显示名称': 'Change display name',
  '云端文件暂时不可用，请稍后重试。':
      'The cloud file is temporarily unavailable. Please try again shortly.',
  '云端资料库': 'Cloud library',
  '共 {count} 首曲目 · 可搜索、筛选和排序': '{count} tracks · search, filter and sort',
  '共 {count} 位歌手 · 可搜索、筛选和排序': '{count} artists · search, filter and sort',
  '找到 {visible} 首曲目（云端共 {total} 首）': 'Found {visible} of {total} cloud tracks',
  '找到 {visible} 位歌手（云端共 {total} 首）':
      'Found {visible} artists across {total} cloud tracks',
  '搜索歌名、歌手或专辑': 'Search titles, artists or albums',
  '清除搜索': 'Clear search',
  '曲目': 'Tracks',
  '按歌手': 'By artist',
  '全部': 'All',
  '云端曲目': 'Cloud tracks',
  '音乐': 'Music',
  '已用空间': 'Storage used',
  '{count} 首': '{count} tracks',
  '离线状态，无法连接至云端。本地曲库和播放仍可正常使用。': 'You are offline and cannot reach the cloud. Your local library and playback remain available.',
  '正在读取云端歌曲…': 'Loading cloud tracks…',
  '集中浏览和管理云端曲目。删除仅影响云副本，不会删除本机文件。': 'Browse and manage cloud tracks in one place. Deleting a cloud copy does not delete the local file.',
  '读取中': 'Loading',
  '刷新云内容': 'Refresh cloud content',
  '云空间还没有歌曲。完成一次同步后，歌曲会显示在这里。': 'There are no tracks in cloud storage yet. They will appear here after a sync.',
  '没有匹配的云端曲目。': 'No cloud tracks match your search.',
  '网络不可用。离线状态下不会影响本地曲库、下载内容或正在播放的歌曲。': 'The network is unavailable. Your local library, downloads and current playback still work offline.',
  '导入 {added} 首，跳过 {skipped} 首，失败 {failed} 首':
      'Imported {added}, skipped {skipped}, failed {failed}',
  '{count} 首可智能整理': '{count} tracks can be organized',
  '已更新为“{title}”－{artist}': 'Updated to “{title}” — {artist}',
  '请先在“歌单”中创建一个歌单。': 'Create a playlist from Playlists first.',
  '已加入“{playlist}”': 'Added to “{playlist}”',
  '这首歌已经在该歌单中': 'This track is already in that playlist',
  'library_read_failed':
      'Could not read the local library. Restart Sona and try again.',
  'track_not_persisted':
      'This track has not been saved and cannot be identified.',
  'identification_in_progress': 'This track is already being identified.',
  'identification_file_missing':
      'The local media file could not be found, so it cannot be identified.',
  'identification_fingerprint_match':
      'A match was found from the audio fingerprint.',
  'identification_catalog_fallback_after_fingerprint': 'The fingerprint had no reliable match, so the public catalog was used as a fallback.',
  'identification_catalog_fallback':
      'The file information and public catalog produced a fallback match.',
  'identification_source_local_cleanup': 'Local metadata cleanup',
  'identification_local_cleanup_explanation': 'The public catalog had no reliable match. This suggestion only uses tags and the filename; review it before applying.',
  'identification_local_cleanup_suggested': 'No reliable online result was found. A local cleanup suggestion is available.',
  'identification_no_reliable_result': 'No reliable identification result was found. The original information was kept.',
  'identification_source_acoustid': 'AcoustID audio fingerprint',
  'identification_acoustid_explanation':
      'Matched from the audio content, independently of the filename.',
  'identification_source_musicbrainz': 'MusicBrainz public catalog',
  'identification_musicbrainz_explanation': 'Matched online using the cleaned title, artist and duration rather than an audio fingerprint.',
  'manual_edit': 'Manual edit',
  'cover_file_missing': 'The selected cover image could not be found.',
  'cover_file_type_unsupported': 'Choose a JPG, PNG or WebP image.',
  'cover_file_too_large': 'Cover images must be no larger than 12 MB.',
  'audio_file_required': 'Choose an audio file first.',
  'audio_already_in_library': 'That audio file is already in the library.',
  'unexpected_library_error':
      'The operation did not complete. Please try again.',
  'account_username_invalid': 'Enter a valid username.',
  'account_sign_in_incomplete': 'Sign-in did not complete. Please try again.',
  'account_sign_in_success': 'Signed in. Checking cloud data…',
  'account_username_format_invalid': 'The username format is invalid.',
  'account_sign_up_incomplete': 'The account could not be created. Confirm that email verification is disabled for this cloud project and try again.',
  'account_sign_up_success': 'Account created and signed in.',
  'account_signed_out':
      'Signed out of the cloud account. Local music is unaffected.',
  'account_display_name_synced': 'Display name synced.',
  'account_avatar_uploading': 'Uploading profile picture…',
  'account_avatar_updated': 'Profile picture updated. It will be restored automatically on your other devices.',
  'account_cloud_not_configured': 'Cloud services are not configured.',
  'account_sign_up_disabled': 'Cloud account registration is not available yet. Please try again later.',
  'account_invalid_credentials': 'The username or password is incorrect.',
  'account_username_taken': 'That username is already in use. Choose another.',
  'account_service_unavailable': 'The account service cannot complete this operation right now. Please try again later.',
  'account_avatar_save_failed': 'The profile picture could not be saved to the cloud. Please try again later.',
  'account_profile_update_failed': 'Cloud profile data could not be updated. You are still signed in; please try again later.',
  'account_operation_failed':
      'The operation did not complete. Please try again.',
  '还没有配对唱片': 'No record paired',
  '暂停': 'Pause',
  '播放': 'Play',
  '播放进度': 'Playback position',
  '正在准备 MV 画面': 'Preparing video',
  'MV 画面准备超时，音频仍在播放':
      'Video is taking longer to appear; audio is still playing',
  'MV 画面暂时不可用，音频仍在播放':
      'Video is temporarily unavailable; audio is still playing',
  'MV 已与这首歌配对。': 'Music video paired with this song.',
  '唱片音频已与这支 MV 配对。': 'Record audio paired with this video.',
  '音频配对失败，请确认文件可用。':
      'Could not pair the audio. Make sure the file is available.',
  '请选择音频文件。': 'Choose an audio file.',
  '这首音频已经在曲库中。': 'This audio file is already in the library.',
  '多套明亮皮肤，也可以导入并裁切自己的图片。':
      'Choose from multiple bright themes, or import and crop your own image.',
  '替换视频文件': 'Replace video file',
  '更换关联 MV': 'Change paired video',
  '关联一个 MV': 'Pair a video',
  '解除 MV 配对': 'Unpair video',
  '播放器设置': 'Player settings',
  '睡眠定时、后台播放状态': 'Sleep timer and background playback status',
  '睡眠定时会在时间到后暂停当前播放。': 'The sleep timer pauses playback when time is up.',
  '将在 {duration} 后暂停播放。': 'Playback will pause in {duration}.',
  '{minutes} 分钟': '{minutes} min',
  '自定义': 'Custom',
  '关闭定时': 'Turn off timer',
  '后台播放与系统通知': 'Background playback and system controls',
  'Android 已接入系统媒体服务：支持后台播放、通知栏、耳机与锁屏控制。': 'Android system media controls are active for background playback, notifications, headsets and the lock screen.',
  '自定义定时': 'Custom timer',
  '暂停前播放时长（分钟）': 'Time before pausing (minutes)',
  '例如 90': 'e.g. 90',
  '可设 1–720 分钟': '1–720 minutes',
  '请输入 1 到 720 之间的分钟数': 'Enter a value from 1 to 720 minutes',
  '开始定时': 'Start timer',
  '最小化': 'Minimize',
  '最大化或还原': 'Maximize or restore',
  '切换到唱片播放': 'Switch to record player',
  '关闭播放队列': 'Close play queue',
  '{source} · {count} 首': '{source} · {count} tracks',
  '来自：{source} · {count} 首': 'From: {source} · {count} tracks',
  '唱片': 'Record',
  'MV · 已配对': 'MV · Paired',
  '关联 MV': 'Pair MV',
  '还没有配对 MV': 'No MV paired',
  '返回': 'Back',
  '近7天': 'Last 7 days',
  '本月': 'This month',
  '总排行': 'All time',
  '播放次数': 'Plays',
  ' 次': ' plays',
  '播放满 70% 才记为一次；旧版本记录仅计入总排行。':
      'A play counts after 70%; legacy plays appear only under All time.',
  '这个时间段还没有播放记录': 'No plays in this period yet',
  '完整播放一首歌后，这里会自动生成排行。':
      'Finish listening to a track and your rankings will appear here.',
  'cloud_sign_in_required': 'Sign in to your cloud account first.',
  'cloud_track_recycled': 'Moved “{title}” to the cloud recycle bin.',
  'cloud_track_restored': 'Restored “{title}”.',
  'cloud_sync_planning': 'Preparing the sync plan…',
  'cloud_sync_preview': '{upload} to upload, {download} to download, {playlistDownload} cloud playlists to restore; {unchanged} tracks are already up to date.',
  'cloud_sync_preview_with_skipped': '{upload} to upload, {download} to download, {playlistDownload} cloud playlists to restore; {unchanged} tracks are already up to date. {tooLarge} tracks exceed 50 MB and will remain only on this device.',
  'cloud_sync_connecting': 'Connecting to the cloud…',
  'cloud_syncing_track': 'Syncing “{title}”…',
  'cloud_syncing_rankings': 'Syncing listening rankings…',
  'cloud_syncing_playlists': 'Syncing playlists…',
  'cloud_sync_downloading_tracks': 'Downloading cloud tracks…',
  'cloud_sync_restoring_playlists': 'Restoring cloud playlists…',
  'cloud_sync_complete': 'Sync complete',
  'cloud_sync_complete_changes':
      'Sync complete: {uploaded} uploaded, {downloaded} downloaded.',
  'cloud_sync_complete_changes_with_skipped': 'Sync complete: {uploaded} uploaded, {downloaded} downloaded. {skippedLarge} tracks exceed 50 MB and remain only on this device.',
  'cloud_sync_complete_unchanged':
      'Sync complete: this device and the cloud are already up to date.',
  'cloud_sync_complete_unchanged_with_skipped': 'Sync complete: this device and the cloud are already up to date. {skippedLarge} tracks exceed 50 MB and remain only on this device.',
  'cloud_sync_interrupted':
      'Sync was interrupted. Your local library is unaffected.',
  'cloud_error_offline': 'You are offline and cannot connect to the cloud.',
  'cloud_error_invalid_credentials':
      'Your cloud session has expired. Sign in again.',
  'cloud_error_permission':
      'The cloud rejected this operation. Check your account permissions.',
  'cloud_error_connection':
      'The cloud is temporarily unreachable. Try again later.',
  'cloud_error_schema': 'Cloud data has not been fully configured.',
  'cloud_error_media':
      'This cloud media file is temporarily unavailable. Try again later.',
  'cloud_error_generic': 'Cloud sync could not finish. Try again later.',
  'queue_source_local_library': 'Local library',
  'queue_source_search': 'Search “{query}”',
  'queue_source_favorites': 'Favorites',
  'queue_source_videos': 'Has MV',
  'queue_source_recent': 'Recent plays',
  'queue_source_rankings': 'Listening charts',
  'queue_source_cloud_library': 'Cloud library',
  'queue_source_playlist': 'Playlist “{playlist}”',
  'player_error_engine': 'The player encountered an error. Try again.',
  'player_error_open_track_preserved_previous':
      'Could not play “{title}”. The previous track remains selected.',
  'player_error_audio_focus_denied':
      'Another app is using audio, so playback cannot start yet.',
  'player_error_local_file_missing':
      'The local file for “{title}” could not be found.',
  'player_error_open_local_file':
      'The local file for “{title}” could not be opened.',
  'player_error_open_next_preserved_current': 'Could not play the next track, “{title}”. The current track will keep playing.',
  'player_error_current_removed_from_library':
      'The current track was removed from the library, so playback stopped.',
  '本地音乐': 'Local music',
  '音乐概览 · 数据统计': 'Library overview · listening insights',
  '查看全部': 'View all',
  '导入歌曲 / MV': 'Import music / MV',
  '导入': 'Import',
  '扫描文件夹': 'Scan folder',
  '批量管理 · 已选 {count} 首': 'Batch actions · {count} selected',
  '已选择 {count} 首': '{count} selected',
  '退出多选': 'Exit selection',
  '音频': 'Audio',
  '视频': 'Video',
  '音频＋MV': 'Audio + MV',
  '有 MV': 'Has MV',
  '类型': 'Type',
  '来源': 'Source',
  '时长': 'Duration',
  '这个来源暂时没有歌曲': 'No tracks in this view yet',
  '没有找到符合条件的歌曲': 'No tracks match these filters',
  '这里还没有音乐': 'No music here yet',
  '导入第一首音乐，开始建立你的私人曲库。':
      'Import your first track to start building your private library.',
  '导入第一首歌 / MV': 'Import your first track / MV',
  '把电脑里的 MP3 或 MP4/MV 导进来，建立你的音乐库。': 'Import MP3 music or MP4/MV videos from your computer to build your library.',
  '从曲库移除': 'Remove from library',
  '从曲库移除？': 'Remove from library?',
  '从曲库移除所选歌曲？': 'Remove selected tracks from the library?',
  '移除“{title}”？': 'Remove “{title}”?',
  '“{title}”将不再显示在 Sona 中，原始文件不会被删除。': '“{title}” will no longer appear in Sona. The original file will not be deleted.',
  '只移除“{title}”的曲库记录，不会删除电脑上的原文件。': 'Only the library record for “{title}” will be removed. The original file stays on your computer.',
  '将移除 {count} 首歌曲的曲库记录，不会删除电脑上的原始文件。': 'The library records for {count} tracks will be removed. Original files stay on your computer.',
  '不会删除手机里的原始文件': 'Original files on your phone will not be deleted',
  '确认移除': 'Remove',
  '添加到歌单': 'Add to playlist',
  '添加到哪个歌单？': 'Choose a playlist',
  '请先在“歌单”中新建一个歌单。': 'Create a playlist first.',
  '已添加到“{playlist}”': 'Added to “{playlist}”',
  '已加入 {playlist}': 'Added to {playlist}',
  '我的歌单': 'My playlists',
  '创建你的第一个歌单': 'Create your first playlist',
  '比如通勤、睡前、运动，或者只属于某段时间的音乐。': 'Make one for commuting, bedtime, workouts, or a moment that matters to you.',
  '新建歌单': 'New playlist',
  '新建': 'New',
  '创建': 'Create',
  '歌单名称': 'Playlist name',
  '歌单描述': 'Description',
  '例如：夜晚散步': 'e.g. Evening walk',
  '心情、场景或故事': 'Mood, place or story',
  '添加歌单封面（可选）': 'Add a playlist cover (optional)',
  '点按更换并裁切封面': 'Tap to replace and crop the cover',
  '裁切歌单封面': 'Crop playlist cover',
  '拖动并缩放，保留正方形区域': 'Drag and zoom to keep the square area you want',
  '编辑歌单': 'Edit playlist',
  '编辑': 'Edit',
  '删除歌单': 'Delete playlist',
  '删除歌单？': 'Delete playlist?',
  '“{playlist}”会被删除，但其中的歌曲仍保留在本地曲库。': '“{playlist}” will be deleted, but its tracks will remain in your local library.',
  '保留歌曲和播放次数': 'Keep tracks and play counts',
  '返回我的歌单': 'Back to my playlists',
  '打开歌单': 'Open playlist',
  '歌单操作': 'Playlist actions',
  '歌单 · {playlist}': 'Playlist · {playlist}',
  '歌单《{playlist}》': 'Playlist “{playlist}”',
  '{count} 首歌曲': '{count} tracks',
  '{count} 首歌曲  ·  {size}': '{count} tracks  ·  {size}',
  '{count} 首歌曲 · {description}': '{count} tracks · {description}',
  '这个歌单还是空的。\n点击上方“添加歌曲”开始选择。':
      'This playlist is empty.\nUse Add tracks above to choose music.',
  '还没有歌单': 'No playlists yet',
  '添加歌曲': 'Add tracks',
  '添加歌曲到歌单': 'Add tracks to playlist',
  '添加 {count} 首': 'Add {count}',
  '已加入 {added} 首，跳过 {skipped} 首重复歌曲':
      'Added {added}; skipped {skipped} duplicates',
  '多选歌曲': 'Select tracks',
  '已选 {count} 首': '{count} selected',
  '从歌单移除': 'Remove from playlist',
  '从歌单移除？': 'Remove from playlist?',
  '将从“{playlist}”移除 {count} 首歌曲，原文件仍保留。':
      'Remove {count} tracks from “{playlist}”? Original files will remain.',
  '听满一首歌的一半后，它会出现在这里。':
      'Tracks appear here after you listen past the halfway point.',
  '搜索“{query}”': 'Search “{query}”',
  '我的背景 {index}': 'My background {index}',
  '裁切播放器背景': 'Crop player background',
  '导入自己的背景': 'Import your own background',
  '裁切图片': 'Crop image',
  '拖动图片调整位置，双指或滚轮缩放':
      'Drag to reposition. Pinch or use the mouse wheel to zoom.',
  '裁切失败：{cause}': 'Crop failed: {cause}',
  '已锁定当前播放器比例 {ratio} : 1': 'Locked to the current player ratio, {ratio}:1',
  '处理中': 'Processing',
  '使用这一区域': 'Use this area',
  '列表循环': 'Repeat queue',
  '单曲循环': 'Repeat one',
  '随机播放': 'Shuffle',
  '例如：xxxxxxxxxxx': 'e.g. xxxxxxxxxxx',
  '{count} 次': '{count} plays',
  '鎏光云纱': 'Aurora Veil',
  '流光极彩': 'Prismatic Flow',
  '樱花汽水': 'Sakura Soda',
  '鎏金麦境': 'Golden Fields',
  '青柠软糖': 'Lime Drops',
  '黑胶花信': 'Vinyl Bloom',
  '雾紫星环': 'Violet Orbit',
  '曜石光环': 'Obsidian Halo',
  '熔岩脉冲': 'Lava Pulse',
  '冰晶琉璃': 'Crystal Ice',
  '橙汽跃夏': 'Orange Summer',
  '钛银流界': 'Titanium Flow',
  '醇红夜幕': 'Crimson Night',
  '深海静潮': 'Deep Sea Calm',
};
